# Generated by Django 2.2.12 on 2020-05-07 08:34

from django.db import migrations, models
import ms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0004_auto_20200506_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gateway_image',
            field=models.ImageField(blank=True, null=True, upload_to=ms.models.user_directory_path),
        ),
    ]
